kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: atlantis-clusterrole
  annotations:
    argocd.argoproj.io/sync-wave: "2"
subjects:
- kind: ServiceAccount
  name: atlantis
  namespace: atlantis
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
