metaphor-frontend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: <METAPHOR_FRONTEND_DEVELOPMENT_INGRESS_URL_NO_HTTPS>
        paths:
          - /
    tls:
    - secretName: metaphor-frontend-tls
      hosts:
        - <METAPHOR_FRONTEND_DEVELOPMENT_INGRESS_URL_NO_HTTPS>
