apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '1000'
spec:
  project: default
  source:
    repoURL: <GITOPS_REPO_URL>
    path: registry/<CLUSTER_NAME>/components/sync-waves
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sync-waves
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
