metaphor:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: <METAPHOR_STAGING_INGRESS_URL_NO_HTTPS>
        paths:
          - /
    tls:
    - secretName: metaphor-tls
      hosts:
        - <METAPHOR_STAGING_INGRESS_URL_NO_HTTPS>
  vaultMountPoint: kubefirst
  vaultSecretPath: staging/metaphor
