apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-overlay
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  target:
    name: secret-overlay
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-kv-secret
  refreshInterval: 10s
  dataFrom:
    - extract:
        key: /development/metaphor
