apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: cwft-ci
spec:
  entrypoint: ci-setup-src
  templates:
  - name: ci-setup-src
    outputs:
      artifacts:
      - name: repo-source
        path: /src
    container:
      image: golang:latest
      command: ["/bin/sh", "-c"]
      args: 
      - mkdir /src