apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secrets-backend
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes/kubefirst"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets-operator"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
      - name: c
        image: sverrirab/sleep:latest
        command:
        - /bin/sh
        - -c
        - |
          echo "sleeping for 10 seconds"
          sleep 10
      restartPolicy: Never
  backoffLimit: 1