apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum-components
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: <FULL_GITOPS_REPO_GIT_URL>
    path: components/chartmuseum
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: chartmuseum
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
