apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kusk
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
    addons.kubefirst.io/name: kusk
spec:
  project: default
  source:
    repoURL: <FULL_GITOPS_REPO_GIT_URL>
    path: components/kusk
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kusk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
