# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: argocd-oidc-restart-job
#   namespace: argocd
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: argocd-oidc-restart-job
#   namespace: argocd
# rules:
#   - apiGroups:
#       - apps
#     resources:
#       - deployments
#     verbs:
#       - get
#       - list
#       - watch
#       - create
#       - update
#       - patch
#       - delete
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: argocd-oidc-restart-job
#   namespace: argocd
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: argocd-oidc-restart-job
# subjects:
#   - kind: ServiceAccount
#     name: argocd-oidc-restart-job
#     namespace: argocd
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: '110'
#     argocd.argoproj.io/hook: PostSync
#   name: argocd-oidc-restart-job
#   namespace: argocd
# spec:
#   template:
#     spec:
#       containers:
#         - name: argocd-oidc-restart-job
#           image: public.ecr.aws/bitnami/kubectl:1.24
#           command:
#             - /bin/sh
#             - -c
#             - kubectl -n argocd rollout restart deployment/argocd-server
#       restartPolicy: OnFailure
#       serviceAccountName: argocd-oidc-restart-job

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: argocd-sync-job
#   namespace: argocd
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: argocd-sync-job-admin
#   namespace: argocd
# roleRef:
#   kind: ClusterRole
#   name: admin
#   apiGroup: rbac.authorization.k8s.io
# subjects:
#   - kind: ServiceAccount
#     name: argocd-sync-job
#     namespace: argocd
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   annotations:
#     argocd.argoproj.io/sync-wave: '1'
#     argocd.argoproj.io/hook: PostSync
#   name: sync-argocd
#   namespace: argocd
# spec:
#   template:
#     spec:
#       containers:
#         - name: sync-argocd
#           image: public.ecr.aws/bitnami/kubectl:1.24
#           command:
#             - /bin/sh
#             - -c
#             - "kubectl kustomize https://github.com/kubefirst-me/gitops/registry/clusters/me-rc6/components/argocd\?ref\=main\&timeout=90s | k apply -f -"
#       restartPolicy: OnFailure
